version: '2'
services:
  server:
    image: odoo:9
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - ./config/odoo-v9:/etc/odoo
      - ./data/odoo-v9/addons:/mnt/extra-addons
      - ./data/odoo-v9/filestore:/var/lib/odoo/filestore
    environment:
    - DB_PORT_5432_TCP_ADDR=db
    - DB_PORT_5432_TCP_PORT=5432
    - DB_ENV_POSTGRES_PASSWORD=odoo
    - DB_ENV_POSTGRES_USER=odoo
    ports:
      - '8069:8069'
  db:
    image: postgres:9.5
    volumes:
      - ./data/postgresql-odoo-v9:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
