version: '2'

services:

  odoov8:
    image: odoo:8
    volumes:
      - ./config/odoo-v8:/etc/odoo
      - ./data/odoo-v8/addons:/mnt/extra-addons
      - ./data/odoo-v8/filestore:/var/lib/odoo/filestore
    environment:
      - DB_PORT_5432_TCP_ADDR=db
      - DB_PORT_5432_TCP_PORT=5432
      - DB_ENV_POSTGRES_PASSWORD=odoo
      - DB_ENV_POSTGRES_USER=odoo
    ports:
      - '8070:8069'


  postgresodoo8:
    image: postgres:9.5
    volumes:
      - ./data/postgresql-odoo-v8:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
